//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one image required!.
        /// </summary>
        internal static string ErrAtLeasOneImageRequired {
            get {
                return ResourceManager.GetString("ErrAtLeasOneImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Updating Data!.
        /// </summary>
        internal static string ErrDbUpdate {
            get {
                return ResourceManager.GetString("ErrDbUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is required!.
        /// </summary>
        internal static string ErrNameIsRequired {
            get {
                return ResourceManager.GetString("ErrNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name should contain at least 2 characters!.
        /// </summary>
        internal static string ErrNameLength_2 {
            get {
                return ResourceManager.GetString("ErrNameLength_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error!.
        /// </summary>
        internal static string ErrValidation {
            get {
                return ResourceManager.GetString("ErrValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfull Delete!.
        /// </summary>
        internal static string SuccessDelete {
            get {
                return ResourceManager.GetString("SuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfull Update!.
        /// </summary>
        internal static string SuccessUpdate {
            get {
                return ResourceManager.GetString("SuccessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string TextAbout {
            get {
                return ResourceManager.GetString("TextAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string TextAdd {
            get {
                return ResourceManager.GetString("TextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add camping place.
        /// </summary>
        internal static string TextAddCampingPlace {
            get {
                return ResourceManager.GetString("TextAddCampingPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added by {0}.
        /// </summary>
        internal static string TextAddedBy {
            get {
                return ResourceManager.GetString("TextAddedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add images.
        /// </summary>
        internal static string TextAddImages {
            get {
                return ResourceManager.GetString("TextAddImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All CampingPlaces.
        /// </summary>
        internal static string TextAllCampingPlaces {
            get {
                return ResourceManager.GetString("TextAllCampingPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details about &quot;{0}&quot;.
        /// </summary>
        internal static string TextCampingPlaceDetails {
            get {
                return ResourceManager.GetString("TextCampingPlaceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string TextChangePassword {
            get {
                return ResourceManager.GetString("TextChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to login.
        /// </summary>
        internal static string TextClickToLogIn {
            get {
                return ResourceManager.GetString("TextClickToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string TextCode {
            get {
                return ResourceManager.GetString("TextCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        internal static string TextConfirmEmail {
            get {
                return ResourceManager.GetString("TextConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        internal static string TextConfirmNewPassword {
            get {
                return ResourceManager.GetString("TextConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string TextConfirmPassword {
            get {
                return ResourceManager.GetString("TextConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password change.
        /// </summary>
        internal static string TextConfirmPasswordChange {
            get {
                return ResourceManager.GetString("TextConfirmPasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string TextContacts {
            get {
                return ResourceManager.GetString("TextContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        internal static string TextCurrentPassword {
            get {
                return ResourceManager.GetString("TextCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string TextDescription {
            get {
                return ResourceManager.GetString("TextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        internal static string TextDoNotRememberPassword {
            get {
                return ResourceManager.GetString("TextDoNotRememberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string TextEdit {
            get {
                return ResourceManager.GetString("TextEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit camping place.
        /// </summary>
        internal static string TextEditCampingPlace {
            get {
                return ResourceManager.GetString("TextEditCampingPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string TextEmail {
            get {
                return ResourceManager.GetString("TextEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string TextEnter {
            get {
                return ResourceManager.GetString("TextEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Login.
        /// </summary>
        internal static string TextFailedLogIn {
            get {
                return ResourceManager.GetString("TextFailedLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string TextFirstName {
            get {
                return ResourceManager.GetString("TextFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten password confirmation.
        /// </summary>
        internal static string TextForgottenPasswordConfirmation {
            get {
                return ResourceManager.GetString("TextForgottenPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to Google maps.
        /// </summary>
        internal static string TextGoogleMapsUrl {
            get {
                return ResourceManager.GetString("TextGoogleMapsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has drinking water.
        /// </summary>
        internal static string TextHasWater {
            get {
                return ResourceManager.GetString("TextHasWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello .
        /// </summary>
        internal static string TextHello {
            get {
                return ResourceManager.GetString("TextHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string TextLastName {
            get {
                return ResourceManager.GetString("TextLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        internal static string TextLogOff {
            get {
                return ResourceManager.GetString("TextLogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string TextNewPassword {
            get {
                return ResourceManager.GetString("TextNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string TextPassword {
            get {
                return ResourceManager.GetString("TextPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string TextPhoneNumber {
            get {
                return ResourceManager.GetString("TextPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camping place name.
        /// </summary>
        internal static string TextPlaceName {
            get {
                return ResourceManager.GetString("TextPlaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camping place not found!.
        /// </summary>
        internal static string TextPlaceNotFound {
            get {
                return ResourceManager.GetString("TextPlaceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string TextRegister {
            get {
                return ResourceManager.GetString("TextRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        internal static string TextRegisterAsNewUser {
            get {
                return ResourceManager.GetString("TextRegisterAsNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember browser.
        /// </summary>
        internal static string TextRememberBrowser {
            get {
                return ResourceManager.GetString("TextRememberBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string TextRememberMe {
            get {
                return ResourceManager.GetString("TextRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by name: .
        /// </summary>
        internal static string TextSearchByName {
            get {
                return ResourceManager.GetString("TextSearchByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wild Camping Sites.
        /// </summary>
        internal static string TextTitle {
            get {
                return ResourceManager.GetString("TextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should contain at least {1} characters!.
        /// </summary>
        internal static string WarnPasswordLength {
            get {
                return ResourceManager.GetString("WarnPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match!.
        /// </summary>
        internal static string WarnPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("WarnPasswordsDoNotMatch", resourceCulture);
            }
        }
    }
}
